name: 'Setup Python Environment'
description: 'Setup Python with uv and install MedFusion dependencies'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  extras:
    description: 'Extra dependencies to install (e.g., dev, docs, web)'
    required: false
    default: 'dev'
  cache:
    description: 'Enable pip cache'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: ${{ inputs.cache == 'true' && 'pip' || '' }}

    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Create virtual environment
      shell: bash
      run: uv venv

    - name: Install dependencies
      shell: bash
      run: |
        source .venv/bin/activate
        uv pip install -e ".[${{ inputs.extras }}]"

    - name: Add venv to PATH
      shell: bash
      run: echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
