name: 'Setup Python Environment'
description: 'Setup Python with uv and install MedFusion dependencies'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  extras:
    description: 'Extra dependencies to install (e.g., dev, docs, web)'
    required: false
    default: 'dev'
  cache:
    description: 'Enable pip cache'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Add uv to PATH
      shell: bash
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Create virtual environment and install dependencies
      shell: bash
      run: |
        uv venv
        uv pip install -e ".[${{ inputs.extras }}]"

    - name: Activate virtual environment
      shell: bash
      run: |
        echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/.venv" >> $GITHUB_ENV
</text>
