name: "Setup Python Environment"
description: "Setup Python with uv and install MedFusion dependencies"
inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.11"
  extras:
    description: "Extra dependencies to install (e.g., dev, docs, web)"
    required: false
    default: "dev"
  cache:
    description: "Enable pip cache"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv and setup environment
      shell: bash
      run: |
        # Install uv
        curl -LsSf https://astral.sh/uv/install.sh | sh

        # Add uv to PATH for this step
        export PATH="$HOME/.cargo/bin:$PATH"

        # Add uv to PATH for subsequent steps
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

        # Create virtual environment and install dependencies
        uv venv
        uv pip install -e ".[${{ inputs.extras }}]"

        # Activate virtual environment for subsequent steps
        echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/.venv" >> $GITHUB_ENV
