import { useState } from 'react';
import { Card, Steps, Button, Space, message, Divider } from 'antd';
import { SaveOutlined, PlayCircleOutlined, DownloadOutlined } from '@ant-design/icons';
import BackboneSelector from '@/components/config/BackboneSelector';
import FusionSelector from '@/components/config/FusionSelector';
import AggregatorSelector from '@/components/config/AggregatorSelector';
import HyperparameterEditor from '@/components/config/HyperparameterEditor';
import TemplateLibrary from '@/components/config/TemplateLibrary';
import ConfigPreview from '@/components/config/ConfigPreview';

const { Step } = Steps;

interface ModelConfig {
  backbone: {
    type: string;
    pretrained: boolean;
    freeze_layers: number;
  };
  fusion: {
    strategy: string;
    hidden_dim?: number;
    num_heads?: number;
  };
  aggregator: {
    type: string;
    params?: Record<string, any>;
  };
  hyperparameters: {
    learning_rate: number;
    batch_size: number;
    epochs: number;
    optimizer: string;
    scheduler?: string;
    weight_decay: number;
  };
  training: {
    mixed_precision: boolean;
    gradient_accumulation_steps: number;
    early_stopping_patience: number;
  };
}

const defaultConfig: ModelConfig = {
  backbone: {
    type: 'resnet50',
    pretrained: true,
    freeze_layers: 0,
  },
  fusion: {
    strategy: 'concatenate',
  },
  aggregator: {
    type: 'mean',
  },
  hyperparameters: {
    learning_rate: 0.001,
    batch_size: 32,
    epochs: 100,
    optimizer: 'adam',
    weight_decay: 0.0001,
  },
  training: {
    mixed_precision: true,
    gradient_accumulation_steps: 1,
    early_stopping_patience: 10,
  },
};

export default function ConfigGenerator() {
  const [currentStep, setCurrentStep] = useState(0);
  const [config, setConfig] = useState<ModelConfig>(defaultConfig);
  const [loading, setLoading] = useState(false);

  const steps = [
    {
      title: '选择 Backbone',
      description: '选择视觉骨干网络',
    },
    {
      title: '配置 Fusion',
      description: '选择融合策略',
    },
    {
      title: '配置 Aggregator',
      description: '选择聚合器',
    },
    {
      title: '调整超参数',
      description: '配置训练参数',
    },
    {
      title: '预览和导出',
      description: '查看配置并导出',
    },
  ];

  const handleBackboneChange = (backbone: ModelConfig['backbone']) => {
    setConfig({ ...config, backbone });
  };

  const handleFusionChange = (fusion: ModelConfig['fusion']) => {
    setConfig({ ...config, fusion });
  };

  const handleAggregatorChange = (aggregator: ModelConfig['aggregator']) => {
    setConfig({ ...config, aggregator });
  };

  const handleHyperparameterChange = (hyperparameters: ModelConfig['hyperparameters'], training: ModelConfig['training']) => {
    setConfig({ ...config, hyperparameters, training });
  };

  const handleTemplateLoad = (template: ModelConfig) => {
    setConfig(template);
    message.success('模板加载成功');
  };

  const handleSaveConfig = async () => {
    setLoading(true);
    try {
      // TODO: 调用 API 保存配置
      await new Promise(resolve => setTimeout(resolve, 1000));
      message.success('配置保存成功');
    } catch (error) {
      message.error('配置保存失败');
    } finally {
      setLoading(false);
    }
  };

  const handleExportYAML = () => {
    // 生成 YAML 格式的配置
    const yaml = generateYAML(config);
    const blob = new Blob([yaml], { type: 'text/yaml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'config.yaml';
    a.click();
    URL.revokeObjectURL(url);
    message.success('配置已导出');
  };

  const handleStartTraining = async () => {
    setLoading(true);
    try {
      // TODO: 调用 API 启动训练
      await new Promise(resolve => setTimeout(resolve, 1000));
      message.success('训练任务已启动');
    } catch (error) {
      message.error('启动训练失败');
    } finally {
      setLoading(false);
    }
  };

  const generateYAML = (config: ModelConfig): string => {
    // 简单的 YAML 生成（实际应该使用专门的库）
    return `# MedFusion Configuration
# Generated by Config Generator

model:
  backbone:
    type: ${config.backbone.type}
    pretrained: ${config.backbone.pretrained}
    freeze_layers: ${config.backbone.freeze_layers}

  fusion:
    strategy: ${config.fusion.strategy}
    ${config.fusion.hidden_dim ? `hidden_dim: ${config.fusion.hidden_dim}` : ''}
    ${config.fusion.num_heads ? `num_heads: ${config.fusion.num_heads}` : ''}

  aggregator:
    type: ${config.aggregator.type}

training:
  hyperparameters:
    learning_rate: ${config.hyperparameters.learning_rate}
    batch_size: ${config.hyperparameters.batch_size}
    epochs: ${config.hyperparameters.epochs}
    optimizer: ${config.hyperparameters.optimizer}
    ${config.hyperparameters.scheduler ? `scheduler: ${config.hyperparameters.scheduler}` : ''}
    weight_decay: ${config.hyperparameters.weight_decay}

  mixed_precision: ${config.training.mixed_precision}
  gradient_accumulation_steps: ${config.training.gradient_accumulation_steps}
  early_stopping_patience: ${config.training.early_stopping_patience}
`;
  };

  const renderStepContent = () => {
    switch (currentStep) {
      case 0:
        return (
          <BackboneSelector
            value={config.backbone}
            onChange={handleBackboneChange}
          />
        );
      case 1:
        return (
          <FusionSelector
            value={config.fusion}
            onChange={handleFusionChange}
          />
        );
      case 2:
        return (
          <AggregatorSelector
            value={config.aggregator}
            onChange={handleAggregatorChange}
          />
        );
      case 3:
        return (
          <HyperparameterEditor
            hyperparameters={config.hyperparameters}
            training={config.training}
            onChange={handleHyperparameterChange}
          />
        );
      case 4:
        return (
          <ConfigPreview
            config={config}
            onExport={handleExportYAML}
          />
        );
      default:
        return null;
    }
  };

  return (
    <div style={{ padding: '24px' }}>
      <Card
        title="可视化配置生成器"
        extra={
          <Space>
            <Button
              icon={<SaveOutlined />}
              onClick={handleSaveConfig}
              loading={loading}
            >
              保存配置
            </Button>
            <Button
              type="primary"
              icon={<PlayCircleOutlined />}
              onClick={handleStartTraining}
              loading={loading}
            >
              启动训练
            </Button>
          </Space>
        }
      >
        <Space direction="vertical" size="large" style={{ width: '100%' }}>
          {/* 模板库 */}
          <Card size="small" title="快速开始">
            <TemplateLibrary onLoad={handleTemplateLoad} />
          </Card>

          <Divider />

          {/* 步骤导航 */}
          <Steps current={currentStep} onChange={setCurrentStep}>
            {steps.map((step) => (
              <Step key={step.title} title={step.title} description={step.description} />
            ))}
          </Steps>

          {/* 步骤内容 */}
          <div style={{ minHeight: '400px', marginTop: '24px' }}>
            {renderStepContent()}
          </div>

          {/* 导航按钮 */}
          <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '24px' }}>
            <Button
              disabled={currentStep === 0}
              onClick={() => setCurrentStep(currentStep - 1)}
            >
              上一步
            </Button>
            <Button
              type="primary"
              disabled={currentStep === steps.length - 1}
              onClick={() => setCurrentStep(currentStep + 1)}
            >
              下一步
            </Button>
          </div>
        </Space>
      </Card>
    </div>
  );
}
