import { Card, Descriptions, Space, Button, Typography, Tag, Divider } from 'antd';
import { DownloadOutlined, CopyOutlined } from '@ant-design/icons';
import { message } from 'antd';

const { Text, Paragraph } = Typography;

interface ConfigPreviewProps {
  config: {
    backbone: {
      type: string;
      pretrained: boolean;
      freeze_layers: number;
    };
    fusion: {
      strategy: string;
      hidden_dim?: number;
      num_heads?: number;
    };
    aggregator: {
      type: string;
      params?: Record<string, any>;
    };
    hyperparameters: {
      learning_rate: number;
      batch_size: number;
      epochs: number;
      optimizer: string;
      scheduler?: string;
      weight_decay: number;
    };
    training: {
      mixed_precision: boolean;
      gradient_accumulation_steps: number;
      early_stopping_patience: number;
    };
  };
  onExport: () => void;
}

export default function ConfigPreview({ config, onExport }: ConfigPreviewProps) {
  const handleCopyYAML = () => {
    const yaml = generateYAML(config);
    navigator.clipboard.writeText(yaml);
    message.success('配置已复制到剪贴板');
  };

  const generateYAML = (config: any): string => {
    return `# MedFusion Configuration
# Generated by Config Generator

model:
  backbone:
    type: ${config.backbone.type}
    pretrained: ${config.backbone.pretrained}
    freeze_layers: ${config.backbone.freeze_layers}

  fusion:
    strategy: ${config.fusion.strategy}
${config.fusion.hidden_dim ? `    hidden_dim: ${config.fusion.hidden_dim}` : ''}
${config.fusion.num_heads ? `    num_heads: ${config.fusion.num_heads}` : ''}

  aggregator:
    type: ${config.aggregator.type}
${config.aggregator.params?.hidden_dim ? `    hidden_dim: ${config.aggregator.params.hidden_dim}` : ''}
${config.aggregator.params?.num_heads ? `    num_heads: ${config.aggregator.params.num_heads}` : ''}

training:
  hyperparameters:
    learning_rate: ${config.hyperparameters.learning_rate}
    batch_size: ${config.hyperparameters.batch_size}
    epochs: ${config.hyperparameters.epochs}
    optimizer: ${config.hyperparameters.optimizer}
${config.hyperparameters.scheduler ? `    scheduler: ${config.hyperparameters.scheduler}` : ''}
    weight_decay: ${config.hyperparameters.weight_decay}

  mixed_precision: ${config.training.mixed_precision}
  gradient_accumulation_steps: ${config.training.gradient_accumulation_steps}
  early_stopping_patience: ${config.training.early_stopping_patience}
`;
  };

  return (
    <Space direction="vertical" size="large" style={{ width: '100%' }}>
      {/* 配置总览 */}
      <Card title="配置总览" size="small">
        <Descriptions column={2} bordered size="small">
          <Descriptions.Item label="Backbone">
            <Space>
              <Text strong>{config.backbone.type}</Text>
              {config.backbone.pretrained && <Tag color="blue">预训练</Tag>}
              {config.backbone.freeze_layers > 0 && (
                <Tag color="orange">冻结 {config.backbone.freeze_layers} 层</Tag>
              )}
            </Space>
          </Descriptions.Item>

          <Descriptions.Item label="Fusion 策略">
            <Space>
              <Text strong>{config.fusion.strategy}</Text>
              {config.fusion.hidden_dim && (
                <Tag>dim: {config.fusion.hidden_dim}</Tag>
              )}
              {config.fusion.num_heads && (
                <Tag>heads: {config.fusion.num_heads}</Tag>
              )}
            </Space>
          </Descriptions.Item>

          <Descriptions.Item label="Aggregator">
            <Space>
              <Text strong>{config.aggregator.type}</Text>
              {config.aggregator.params?.hidden_dim && (
                <Tag>dim: {config.aggregator.params.hidden_dim}</Tag>
              )}
              {config.aggregator.params?.num_heads && (
                <Tag>heads: {config.aggregator.params.num_heads}</Tag>
              )}
            </Space>
          </Descriptions.Item>

          <Descriptions.Item label="优化器">
            <Text strong>{config.hyperparameters.optimizer.toUpperCase()}</Text>
          </Descriptions.Item>

          <Descriptions.Item label="学习率">
            {config.hyperparameters.learning_rate}
          </Descriptions.Item>

          <Descriptions.Item label="Batch Size">
            {config.hyperparameters.batch_size} × {config.training.gradient_accumulation_steps} = {' '}
            <Text strong>{config.hyperparameters.batch_size * config.training.gradient_accumulation_steps}</Text>
            {' '}(等效)
          </Descriptions.Item>

          <Descriptions.Item label="训练轮数">
            {config.hyperparameters.epochs}
          </Descriptions.Item>

          <Descriptions.Item label="早停耐心值">
            {config.training.early_stopping_patience}
          </Descriptions.Item>

          <Descriptions.Item label="权重衰减">
            {config.hyperparameters.weight_decay}
          </Descriptions.Item>

          <Descriptions.Item label="学习率调度器">
            {config.hyperparameters.scheduler || '不使用'}
          </Descriptions.Item>

          <Descriptions.Item label="混合精度">
            {config.training.mixed_precision ? (
              <Tag color="green">✅ 开启</Tag>
            ) : (
              <Tag>❌ 关闭</Tag>
            )}
          </Descriptions.Item>

          <Descriptions.Item label="梯度累积">
            {config.training.gradient_accumulation_steps} 步
          </Descriptions.Item>
        </Descriptions>
      </Card>

      <Divider />

      {/* YAML 预览 */}
      <Card
        title="YAML 配置预览"
        size="small"
        extra={
          <Space>
            <Button
              icon={<CopyOutlined />}
              onClick={handleCopyYAML}
              size="small"
            >
              复制
            </Button>
            <Button
              type="primary"
              icon={<DownloadOutlined />}
              onClick={onExport}
              size="small"
            >
              导出
            </Button>
          </Space>
        }
      >
        <pre
          style={{
            backgroundColor: '#f5f5f5',
            padding: '16px',
            borderRadius: '4px',
            overflow: 'auto',
            maxHeight: '400px',
            fontSize: '12px',
            lineHeight: '1.6',
          }}
        >
          {generateYAML(config)}
        </pre>
      </Card>

      {/* 使用提示 */}
      <Card size="small" style={{ backgroundColor: '#f0f5ff' }}>
        <Space direction="vertical" size="small">
          <Text strong>💡 使用提示</Text>
          <Paragraph style={{ margin: 0, fontSize: '12px', color: '#666' }}>
            1. 点击"导出"按钮下载 YAML 配置文件
          </Paragraph>
          <Paragraph style={{ margin: 0, fontSize: '12px', color: '#666' }}>
            2. 使用 CLI 命令启动训练: <Text code>medfusion train --config config.yaml</Text>
          </Paragraph>
          <Paragraph style={{ margin: 0, fontSize: '12px', color: '#666' }}>
            3. 或点击"启动训练"按钮直接在 Web UI 中启动
          </Paragraph>
        </Space>
      </Card>
    </Space>
  );
}
